# xpectr::gxs_selection("ipak('vegan')")

## Testing 'ipak('vegan')'                                                  ####
## Initially generated by xpectr
xpectr::set_test_seed(42)
# Assigning output
output_19148 <- ipak("vegan")
# Testing class
expect_equal(
  class(output_19148),
  "logical",
  fixed = TRUE
)
# Testing type
expect_type(
  output_19148,
  type = "logical"
)
# Testing values
expect_equal(
  output_19148,
  c(vegan = TRUE)
)
# Testing names
expect_equal(
  names(output_19148),
  "vegan",
  fixed = TRUE
)
# Testing length
expect_equal(
  length(output_19148),
  1L
)
# Testing sum of element lengths
expect_equal(
  sum(xpectr::element_lengths(output_19148)),
  1L
)
## Finished testing 'ipak('vegan')'                                         ####
